### ISSUE TITLE
gallery not displaying images

### ISSUE THREAD

**Issue by hutou** [i-lateral/silverstripe-gallery#1]
Since last update (via composer), nor images neither navigation buttons (arrows) are displayed. I can only see thumbnails at the bottom of the page.

**Comment by mlewis-everley** [comment]
Hi Hutou,

I am not sure why, but it seems that GitHub doesn't notify me if an issue comes through :-s.

The only changes I made at that time were adding drag and drop support, so you might have to add the sortablefile module?

I am not aware of any changes to templates, but if you have overwritten the default template then that may also need updating? 

I have also more recently updated this module to add support for Flexslider over the older adgallery, as adgallery didn't have very good support in IE and wasn't responsive.

Cheers,

Mo

**Comment by mlewis-everley** [comment]
Closing as no response.
