### ISSUE TITLE
'SortableUploadField' not found in 

### ISSUE THREAD

**Issue by SqualaDesign** [i-lateral/silverstripe-gallery#4]
Fatal error
: Class 'SortableUploadField' not found in 
/gallery/code/model/GalleryPage.php
on line 
37

**Comment by mlewis-everley** [comment]
Sounds like you don't have the sortablefile module installed?

https://github.com/bummzack/sortablefile

It is required for drag and drop re-ordering of images.

**Comment by mlewis-everley** [comment]
Closing as no response has been made.
