### ISSUE TITLE
SilverStripe 4 compatibility

### ISSUE THREAD

**Issue by JorisDebonnet** [i-lateral/silverstripe-gallery#5]
Hi! This looks like the most active silverstripe gallery module (since a month ago anyway), so I thought I'd check for SilverStripe 4 compatibility here. Are there any plans for it yet?

**Comment by mlewis-everley** [comment]
Hi Joris,

The 2 branch is for SS4 support, you can install to the latest tag (2.1.1)
for a stable version.

Mo

**Comment by JorisDebonnet** [comment]
Thanks! Not sure how I missed that, perhaps I was looking at master.
