### ISSUE TITLE
$Images' items in Gallery.ss are empty

### ISSUE THREAD

**Issue by JorisDebonnet** [i-lateral/silverstripe-gallery#7]
I am using 2.1.1. 

The `<img>` tags on a GalleryPage are generated with empty attributes. I have been able to find that the issue is in GalleryPageController::Gallery in the way the Images variable is filled. This uses ArrayList and ArrayData, and apparently that doesn't work. I have not yet been able to determine why. 

[edited out out-of-date details]

If I have three images in the Gallery, it will in fact go into that loop three times, but without any data. So it does not even print the "testing". Somehow, that ArrayData isn't doing what is expected.

Do you have any insight on how to fix this?

**Comment by JorisDebonnet** [comment]
Hmm... seems like the issue was elsewhere. The generation of GalleryThumbnail did not work because `ThumbnailResizeType` does not receive a default value, so GalleryThumbnail returned "false".

**Comment by mlewis-everley** [comment]
Cool, cheers for this, both pull requests seem fine so have merged, will do a little bit more testing and then issue a new version!
